version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - restore_cache:
          keys:
             - v1-dependencies-{{checksum "package.json"}}  
             - v1-dependencies-
      - run:
          name: install dependencies
          command : npm install 
      - save_cache:
          paths:
            - node_modules
          key : v1-dependencies-{{checksum "package.json"}}  
      - run :
          name : push to git hub
          command : git push -u new  main
      - run :
          name : deploy
          command : vercel --prod    

workflows:
      build_deploy:
         jobs:
           - deploy