version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
             - v1-dependencies-{{checksum "package.json"}}  
             - v1-dependencies-
      - run:
          name: install dependencies
          command : npm install 
      - save_cache:
          paths:
            - node_modules
          key : v1-dependencies-{{checksum "package.json"}}  
      - run :
          name : install vercel 
          command : npm i -g vercel
      - run :
          name : version vercel
          command : vercel --version  
      - run :
          name : deploy
          command : vercel --prod    

workflows:
      build_deploy:
         jobs:
           - deploy